### ISSUE TITLE
overriding emit fails

### ISSUE THREAD

**Issue by uwesimm** [tunnelvisionlabs/antlr4ts#342]
hi,

apparently i'm unable to override Lexer::emit and i cannot really make sense out of it. 
i'm getting a

```
/usr/local/lib/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
main.ts (6,7): Class 'mLexer' incorrectly extends base class 'ExprLexer'.
  Types of property 'emit' are incompatible.
    Type '(token: Token) => Token' is not assignable to type '{ (token: Token): Token; (): Token; }'. (2415)
main.ts (9,15): Property 'buffer' does not exist on type 'mLexer'. (2339)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:307:15)
    at /usr/local/lib/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
```

you may try https://github.com/uwesimm/antlr4ts-issue

(if this is a user failure or lack of my typescript knowledge please let me know)
/uwe

**Comment by sharwell** [comment]
Your override has to handle both `emit` signatures:

```
emit(token: Token): Token;
emit(): Token;
```

It might look like this:

```
emit(token?: Token): Token {
  if (token) {
    super.emit(token);
    this.buffer.push(token);
    return token;
  } else {
    return super.emit();
  }
}
```

**Comment by uwesimm** [comment]
that works.
