### ISSUE TITLE
Parse error in parser interpreter with profiling on

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#399]
When profiling is enabled for the parser interpreter then it doesn't finish a parse run cleanly, like it does when profiling is not set to true. Instead I get an error:

```
"RangeError: Maximum call stack size exceeded
	at Uint16Array.slice (<anonymous>)
	at new BitSet (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/misc/BitSet.js:97:38)
	at BitSet.clone (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/misc/BitSet.js:636:16)
	at ATNConfigSet.getRepresentedAlternatives (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ATNConfigSet.js:109:54)
	at ProfilingATNSimulator.reportAttemptingFullContext (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:194:73)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:563:30)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ProfilingATNSimulator.js:70:29)
	at ProfilingATNSimulator.execDFA (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:566:33)
	at ProfilingATNSimulator.adaptivePredict (/Volumes/Extern/Work/projects/vscode-antlr4/node_modules/antlr4ts/atn/ParserATNSimulator.js:379:28)"
```

Here's how I use profiling:

```typescript
            await this.parser.setProfile(true);
            try {
                this.parseTree = this.parser!.parse(startRuleIndex);
                let info = await this.parser!.parseInfo;
            } finally {
                this.sendEvent("end");
            }

```

The grammar used for the interpreter is:

```
grammar Example;

start:
    digits letters digits letters EOF
;

letters: LETTER+;
digits: DIGIT*;

LETTER: [a-zA-Z];
DIGIT:  [0-9];

WS: [ \n\t\b] -> skip;
```

**Comment by sharwell** [comment]
Oh, interesting! 😆
