### ISSUE TITLE
antlr4ts failing on Ubuntu

### ISSUE THREAD

**Issue by ForrestHurley** [tunnelvisionlabs/antlr4ts#428]
Anyone have any idea what I am doing wrong or how to debug it? This is a project which works on windows, but when I try to compile the grammar, it fails on ubuntu. I have tried purging the npm cache, deleting the node_modules directory, and reinstalling, but that did not help.

antlr4ts 0.5.0-dev3 is set as a dependency along with antlr4ts-cli and antlr4 4.7.2.

```text
user_name@ubuntu:~/Documents/antlr_test$ npm run antlr4ts_compile

> systemverilog@0.9.1 antlr4ts_compile /home/forrest/Documents/antlr_test
> antlr4ts -visitor ./src/compiling/ANTLR/grammar/SystemVerilog.g4 -o ./src/compiling/ANTLR/grammar/build

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! systemverilog@0.9.1 antlr4ts_compile: `antlr4ts -visitor ./src/compiling/ANTLR/grammar/SystemVerilog.g4 -o ./src/compiling/ANTLR/grammar/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the systemverilog@0.9.1 antlr4ts_compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user_name/.npm/_logs/2019-11-13T00_38_09_080Z-debug.log
```

**Comment by GeorgDangl** [comment]
Is Java installed and available via the `java` command?

**Comment by ForrestHurley** [comment]
That was the problem. As soon as I installed java, it worked. Thank you!
