### ISSUE TITLE
Circular dependencies in Parser and Lexer?

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#461]
I've done some rework of how the import statements are organized, I think I'm running into the circular dependency problem, with runtime errors shown below. 

Tracing through it with a debugger, it seems the object being returned as the façade for `import {whatever} from "antlr4ts"`, does not have members `Parser` nor `Lexer`, and thus the generated wrapper classes (like `XPathLexer`) can't call the superclass constructor.  

Wondering why these two classes in particular are missing, it seems to me like there are circular references between `Lexer` and `LexerATNSimulator` that might be related.  I'm not sure.    

I remember these circular dependency issues could be very difficult to predict, load order effecting things.   I'll work on it and update...

```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\code\antlr4ts\runtime\typescript\src\tree\xpath\XPathLexer.ts:17:33)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\code\antlr4ts\runtime\typescript\src\tree\xpath\XPath.ts:16:1)      
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\code\antlr4ts\runtime\typescript\src\tree\xpath\index.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\code\antlr4ts\runtime\typescript\src\tree\index.ts:18:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\code\antlr4ts\runtime\typescript\src\index.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\code\antlr4ts\test\src\TestArray2DHashSet.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at requireOrImport (C:\code\antlr4ts\node_modules\mocha\lib\esm-utils.js:15:12)
    at Object.loadFilesAsync (C:\code\antlr4ts\node_modules\mocha\lib\esm-utils.js:28:26)
    at Mocha.loadFilesAsync (C:\code\antlr4ts\node_modules\mocha\lib\mocha.js:351:19)
    at singleRun (C:\code\antlr4ts\node_modules\mocha\lib\cli\run-helpers.js:107:15)
    at C:\code\antlr4ts\node_modules\mocha\lib\cli\run-helpers.js:144:11
    at Object.handler (C:\code\antlr4ts\node_modules\mocha\lib\cli\run.js:306:11)
    at Object.runCommand (C:\code\antlr4ts\node_modules\mocha\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\code\antlr4ts\node_modules\mocha\node_modules\yargs\yargs.js:1096:28)       
    at Object.parse (C:\code\antlr4ts\node_modules\mocha\node_modules\yargs\yargs.js:575:25)
    at Object.main (C:\code\antlr4ts\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\code\antlr4ts\node_modules\mocha\bin\_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:1155:14)
    at Object..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by BurtHarris** [comment]
Resolved by careful ordering of imports in **index.ts**.
